---
# =============================================================================
# Ansible Role: NFTables - Logrotate Tasks
# =============================================================================
# This file configures log rotation for NFTables log files to ensure they
# don't grow indefinitely and are properly archived. It:
# 1. Creates the archive directory if it doesn't exist
# 2. Deploys a logrotate configuration file with specified options
#
# The logrotate configuration is customizable via role variables.
# =============================================================================

# -----------------------------------------------------------------------------
# 1. Archive Directory Setup
# -----------------------------------------------------------------------------
- name: NFTables | logrotate | Check if archive log directory exists
  become: true
  ansible.builtin.stat:
    path: "{{ nftables_logrotate_options.archive_directory_path }}"
  register: _archive_log_directory_stat_

- name: NFTables | logrotate | Create archive log directory if needed
  become: true
  ansible.builtin.file:
    path: "{{ nftables_logrotate_options.archive_directory_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: >
    not _archive_log_directory_stat_.stat.exists

# -----------------------------------------------------------------------------
# 2. Logrotate Configuration
# -----------------------------------------------------------------------------
- name: NFTables | logrotate | Deploy logrotate configuration file
  become: true
  ansible.builtin.template:
    src: "templates/logrotate/nftables.j2"
    dest: "{{ nftables_logrotate_config_path }}"
    owner: root
    group: root
    mode: "0644"
