---
# =============================================================================
# Ansible Role: NFTables - Tasks: Prerequisites
# =============================================================================
# Prepares the system environment by configuring rsyslog and disabling conflicting services.
# =============================================================================

# -----------------------------------------------------------------------------
# 1. Rsyslog Setup
# -----------------------------------------------------------------------------
- name: NFTables | prerequisites | Install rsyslog package
  become: true
  ansible.builtin.package:
    name: rsyslog
    state: present
  register: _nftables_rsyslog_package_

- name: NFTables | prerequisites | Ensure service is enabled
  become: true
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true
  register: _nftables_rsyslog_status_

# -----------------------------------------------------------------------------
# 2. Conflicting Firewall Services
# -----------------------------------------------------------------------------
- name: NFTables | prerequisites | Gather service facts
  become: true
  ansible.builtin.service_facts:

- name: NFTables | prerequisites | Stop and disable conflicting firewall services
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - firewalld
    - iptables
    - netfilter-persistent
    - ufw
  loop_control:
    label: "{{ item }}"
  retries: 3
  delay: 5
  when: >
    ansible_facts.services[item + '.service'] is defined and
    (
      ansible_facts.services[item + '.service'].state == 'running' or
      ansible_facts.services[item + '.service'].status == 'enabled'
    )
