---
# =============================================================================
# Ansible Role: NFTables - Handlers
# =============================================================================
# This file defines handlers that can be triggered by tasks to perform
# service management operations. Handlers run only once at the end of plays,
# even if notified multiple times.
#
# Each handler restarts a specific service after configuration changes.
# =============================================================================

# -----------------------------------------------------------------------------
# Service Handlers
# -----------------------------------------------------------------------------
- name: NFTables | handlers | Restart rsyslog service
  become: true
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  when: >
    not (ansible_virtualization_type is defined and
      ansible_virtualization_type == 'docker')

- name: NFTables | handlers | Restart nftables service
  become: true
  ansible.builtin.service:
    name: "{{ nftables_service_name }}"
    state: restarted
