# =============================================================================
# Ansible Role: NFTables - Molecule Convergence Playbook
# =============================================================================
# This playbook executes the main role functionality in the test environment.
# It performs the following steps:
# - Updates package repositories
# - Ensures system readiness
# - Executes the NFTables role with test configuration
#
# Flow:
# 1. Update package cache
# 2. Wait for system initialization
# 3. Apply NFTables role with test variables
# =============================================================================

---
# -----------------------------------------------------------------------------
# 1. Pre-Tasks Setup
# -----------------------------------------------------------------------------
- name: molecule | Converge
  hosts: all

  pre_tasks:
    # Package Cache Update
    - name: Converge | Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: >
        ansible_os_family == "Debian"

    - name: Converge | Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when: >
        ansible_os_family == "RedHat"

    # System Initialization
    - name: Converge | Wait for systemd to complete initialization
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: >
        ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

# -----------------------------------------------------------------------------
# 2. Role Execution with Test Variables
# -----------------------------------------------------------------------------
  vars:
    # Test configuration for NFTables role
    nftables_configure_logrotate: true
    nftables_service_enabled: true

    # Enable common test rules
    nftables_user_defined_input_enabled: true
    nftables_user_defined_output_enabled: true

    # Test input rules
    nftables_user_defined_input_rules:
      - protocol: "tcp"
        port: "22"
        action: "accept"
        counter: true
        log: true
        comment: "Allow SSH for testing"

    # Test output rules
    nftables_user_defined_output_rules:
      - protocol: "udp"
        port: "53"
        action: "accept"
        counter: true
        log: false
        comment: "Allow DNS outbound for testing"
      - protocol: "tcp"
        port: "80,443"
        action: "accept"
        counter: true
        log: false
        comment: "Allow HTTP/HTTPS outbound for testing"

    nftables_reboot_required: false

  roles:
    - role: grzegorzfranus.nftables
